# fly.toml file generated for zigliki-hi-bot on 2023-03-22T17:52:00-04:00

app = "zigliki-hi-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yyz"
processes = []

[build]
  builder = "heroku/buildpacks:20"

[experimental]
  auto_rollback = true
